### ISSUE TITLE
Doesn't build with recent Phobos.

### ISSUE THREAD

**Issue by arrowd** [ximion/appstream-generator#109]
Starting from version 1.101 Phobos removed `std.xml` module which is used by the RPM backend, making the build with new compiler impossible.

**Comment by ximion** [comment]
Yeah, we either need to drop the backend or make it work using GMarkup as a parser... (I'd like to avoid using the undead library).

**Comment by ximion** [comment]
With the patch above you can disable building support for RPM repositories.

**Comment by arrowd** [comment]
Great, thanks!.
