### ISSUE TITLE
Uses the oldest .deb in archive instead of the newest

### ISSUE THREAD

**Issue by jriddell** [ximion/appstream-generator#30]
In KDE neon we are running appstream-generator over our archive which includes many old builds.  Appstream-generator seems to take the oldest build in the archive and ignore newer ones.  This means fixes to the appstream files don't get used.
http://build.neon.kde.org/view/mgmt/job/mgmt_appstream-generator/97/console
18:59:05 2016-11-02 18:58:51 - INFO: Processed minuet/16.04.3-0neon+16.04+build8/amd64, components: 0, hints: 1
But minuet is on 16.08.2-0neon+16.04+build17 which includes many fixes in the appstream file.

**Comment by apachelogger** [comment]
@ximion is this intentional? and if so can we get a flag to override this via the config?

**Comment by ximion** [comment]
@apachelogger If there are multiple packages with different versions but the same name, the components from all of them are included in the final output at time. The client-side however will only pick one, and might pick the older one until it has expired and been removed from the archive.
This usually happens rather quickly, so this wasn't an issue for us so far and we didn't need to do version comparisons and filtering on the input data yet.

**Comment by ximion** [comment]
Please test if this works for you :-)
