### ISSUE TITLE
Support languages tag

### ISSUE THREAD

**Issue by iainlane** [ximion/appstream-generator#37]
I was looking at the kudo code in gnome-software, and the "translated into my languages" thing was reported as a problem in Ubuntu since it was never shown as enabled.

For that to work, we would need to support emitting [the languages tag](https://www.freedesktop.org/software/appstream/docs/sect-AppStream-YAML.html#field-dep11-languages).

Has this been considered before? It would require looking into `.mo' files, which means extracting packages, which is a bit slow. Maybe therefore it should be a feature?

**Comment by ximion** [comment]
Yes to all of your questions ;-)
This is actually already on my todo list, but I wanted you to finish libmo first, then we can use this to read the metadata from .mo files.
Another annoying thing will be finding .mo files reliably (I will probably reserve another db-key in the contents db for this, similarly to what we do with icons, and only ever read the .mo files when the software's metainfo tag has a "translation" tag)

**Comment by Beuc** [comment]
Hi!
Is this tool used for the Debian metadata?
I just hit this issue and it was quite hard to track down.

Here is some discussion about how this feature is implemented in appstream-builder (part of appstream-glib) and Fedora:
https://gitlab.gnome.org/GNOME/gnome-software/issues/583

**Comment by ximion** [comment]
I accept PRs to make this work ;-)
Originally I was waiting for @iainlane 's https://github.com/iainlane/mo library to make implementing this feature much easier, today it just needs someone to do the work.
The localization tag is implemented only for fonts currently.

**Comment by Beuc** [comment]
I have no time to work on this, unfortunately.
AFAIK this already works in Fedora - isn't there a way to grab the working implementation?

**Comment by ximion** [comment]
No, the two programs work very differently, so unfortunately it's not a case of "just copy it".
However, since I am already working on AppStream this weekend, I might be able to at least make a smaller implementation that works with Gettext (Qt translations also don't look that hard, so maybe I'll do these as well)..

**Comment by Beuc** [comment]
Great!
I have a [meta-package](https://appstream.debian.org/sid/main/metainfo/freedink-engine.html) with several gettext domains and a `<translation>` tag, can't wait to see how this plays out :)

**Comment by ximion** [comment]
@Beuc You will have to have a `<translation/>` tag with your gettext domain in the metainfo file for this to work, see https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-translation
As far as I can see, that tag isn't currently present.

**Comment by Beuc** [comment]
Apparently the system didn't import yesterday's release yet.
Also I mistakenly linked above the old non-metapackage (freedink-engine), not the actual metapackage (freedink) which is not present yet.
