### ISSUE TITLE
0.6.5 generates truncated metadata for some packages

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream-generator#47]
With 0.6.5 metadata is incorrectly extracted for some packages, giving a broken xml that is not validated by appstream

**Comment by antonio-rojas** [comment]
Metadata for kdenlive as extracted by asgen 0.6.5. Note the many missing Name fields

[asgen-0.6.5.txt](https://github.com/ximion/appstream-generator/files/1138409/asgen-0.6.5.txt)

**Comment by antonio-rojas** [comment]
Metadata for kdenlive as extracted by asgen 0.6.3

[asgen-0.6.3.txt](https://github.com/ximion/appstream-generator/files/1138411/asgen-0.6.3.txt)

**Comment by antonio-rojas** [comment]
kdenlive metainfo provided by upstream

[kdenlive.txt](https://github.com/ximion/appstream-generator/files/1138414/kdenlive.txt)

**Comment by antonio-rojas** [comment]
Turns out the asgen version is irrelevant, this regressed in appstream 0.11.1. Downgrading to 0.11.0 fixes the metadata extraction

**Comment by ximion** [comment]
Jup, this has to be an AppStream bug.
I will look into it when home.

**Comment by ximion** [comment]
Thanks for reporting this! It was a rather simple mistake done while refactoring the XML code (return -> continue).
Anyway, this has a test now so it won't appear again :-)
