### ISSUE TITLE
Unfindable package after bad packaging

### ISSUE THREAD

**Issue by btkostner** [ximion/appstream-generator#49]
So I had a package in the repository that had no `DEBIAN/md5sum` lines. When I would run `process --force --verbose` the package would be found, but it had no interesting files and would be skipped.

I fixed the package, reuploaded it to the repository, verified it had the `DEBIAN/md5sum` lines, and was included in the repository `packages` file. But after `forget-found --force` and `cleanup`, `appstream-generator` doesn't seem to find the package. There is no mention of it when running `process --force --verbose` even though all the other packages are found.

[Appstream html](https://appstream.elementary.io/appcenter/html/xenial/main/metainfo/index.html)
[Repository Url](http://packages.elementary.io/appcenter/)
[Actual Package link](http://packages.elementary.io/appcenter/pool/main/c/com.github.rickybas.date-countdown/com.github.rickybas.date-countdown_0.1.2_amd64.deb)

Using v0.6.5 built from source
Appstream version 0.11.2 also built from source
Ubuntu xenial 16.04

Will post `appstream-generator` output tonight.

**Comment by ximion** [comment]
Does the package have a higher version than before? Or did you just override the old one with one of the exact same version? In the latter case, this behavior is actually expected and not a bug, since this thing never happens at all in any Debian repository.

**Comment by btkostner** [comment]
It was the same version, but I would expect the `cleanup` or `forget-found` command to clean up any sort of previous history / cache of packages.

**Comment by ximion** [comment]
`forget-found` just (as the name implies) removes found components or the not-found state from a package. We do never read in the file list again, once we processed a package.
The `cleanup` method removes things from the media cache and deletes packages that are not in the `Packages` file anymore.

I could maybe add a new method to completely delete all information we have on a package (could be useful occasionally). But overriding a package with a new one, keeping the version, is evil and should not be done (unless one is testing internally).

**Comment by btkostner** [comment]
I'm going to close this then, as it was just a misunderstanding of what the commands actually do.

**Comment by ximion** [comment]
...which means I really need to add a manpage with the next release
