### ISSUE TITLE
Export data using the same directory hierarchy as the repo

### ISSUE THREAD

**Issue by neilmayhew** [ximion/appstream-generator#5]
The repo expects data to be in a `dep11` subdirectory but `asgen` puts it directly under the directory for the distribution. This stops me from rsyncing the data directly into the `dists` directory of the repo.

The following change fixes this:

```Diff
diff --git a/source/engine.d b/source/engine.d
index ff3837c..f9a960f 100644
--- a/source/engine.d
+++ b/source/engine.d
@@ -216,7 +216,7 @@ public:
         mdataEntries ~= getMetadataHead (suite, section);
 
         // prepare destination
-        auto dataExportDir = buildPath (exportDir, "data", suite.name, section);
+        auto dataExportDir = buildPath (exportDir, "data", suite.name, section, "dep11");
         auto hintsExportDir = buildPath (exportDir, "hints", suite.name, section);
 
         mkdirRecurse (dataExportDir);
```

**Comment by ximion** [comment]
Hmm, not sure if that's useful to do (you can do per-suite syncing even with the old scheme), especially because it adds another, weird directory for people generating XML.
I can't make this default because it would break both Debian and Ubuntu atm, which expect the existing layout...

**Comment by neilmayhew** [comment]
I see your point about per-suite syncing. I guess I can get by without this change.

**Comment by ximion** [comment]
You could also quite easily get this structure by creating a new directory and link the data/suite/section directory as "dep11" wherever you want, then call rsync with its follow-symlinks option.
That would give you the same result.
