### ISSUE TITLE
warning on https->http redirect of screenshot downloads?

### ISSUE THREAD

**Issue by apachelogger** [ximion/appstream-generator#58]
Screenshots that had https as url currently can get redirected to http without any warnings being raised as it seems curl's `get!` simply follows https->http.

As this degrades authenticity of the data it would be prudent to at least raise a warning about this and have authors either use http on the url to begin with or ensure the redirect chain does not drop to http. A MITM attack could inject unwanted art into the final data set, making both the distributor and the software look bad.

**Comment by ximion** [comment]
I don't think this is a super-realistic scenario (MITM attacks on the generator servers), but nevertheless this is a bug that should be closed.
I wasn't aware that Curl does this. We'll need to figure out how to address this, or check if [nicer API](https://github.com/ikod/dlang-requests) handles this scenario better.
