### ISSUE TITLE
font: wrong language is used for sample text

### ISSUE THREAD

**Issue by changwoo** [ximion/appstream-generator#64]
I found with Korean fonts, "bg" seems to be chosen as the language for sample text. I think it's because "bg" is alphabetically first in the supported language list.

```
$ fc-query /usr/share/fonts/truetype/baekmuk/batang.ttf |grep lang
	familylang: "en"(s)
	stylelang: "en"(s)
	fullnamelang: "en"(s)
	lang: bg|fj|ho|ia|ie|io|ko|kum|nr|om|os|ru|sel|so|ss|st|sw|ts|uz|xh|zu|kj|kwm|lg|ms|ng|rn|rw|sn|za(s)
$ 
```

Fonts don't seem to have information to finding out their representitive language. So how about just putting language for sample text in metainfo file?

**Comment by ximion** [comment]
Yeah, font metadata is *hard*.
What you can do at the moment is use two custom values to set the exact text and icon to be used, this is primarily used for symbolic fonts though:
```XML
<custom>
  <value key="FontIconText">∑√</value>
  <value key="FontSampleText">∑ ∮ √ ‖...‖ ⊕ 𝔼 ℕ ⋉</value>
</custom>
```

To explicitly set the supported languages for a font, you should be able to use `<languages/>` in your font metainfo file, see https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-languages for details.
That support isn't implemented yet however, maybe I will be able to work on that this week.

**Comment by ximion** [comment]
I've committed a preliminary patch that deals with this issue. I have an idea for a slightly better version though, which will be added later.
Greetings from Debconf! :-)
