### ISSUE TITLE
font handler should prefer embedded sample string if available

### ISSUE THREAD

**Issue by n8willis** [ximion/appstream-generator#65]
It's good that the font handler tries to be smart about selecting the sample-text string that will be shown to users. 

There is one option it is not currently making use of, however: in OpenType and TrueType fonts, the `name` table includes a field for sample strings at `nameID 19`. If this nameID is present in the font, it means that the designer or publisher has selected the sample string that (hopefully) best shows the relevant characteristics of the font.

It could be identical to a standard pangram, but then again it could be different. So, if present in the binary, it is preferable to an arbitrary string choice.

(The table is detailed here: https://docs.microsoft.com/en-gb/typography/opentype/spec/name#name-ids )

**Comment by ximion** [comment]
This isn't well tested yet, because I don't have a large enough set of fonts for testing.
I will do a run with the Debian archive though, to see if there are any issues.
Thanks for the issue report!
