### ISSUE TITLE
appstream.debian.org claims that scdaemon metainfo file is GPL-licensed, but it is CC0-1.0

### ISSUE THREAD

**Issue by dkg** [ximion/appstream-generator#68]
https://appstream.debian.org/sid/main/issues/scdaemon.html says:

> metainfo-license-invalid

But, [debian/copyright for the source package](https://salsa.debian.org/debian/gnupg2/blob/debian/master/debian/copyright#L79) says:

    Files: debian/org.gnupg.scdaemon.metainfo.xml
    Copyright: 2017 Daniel Kahn Gillmor <dkg@fifthhorseman.net>
    Comment: This file is licensed permissively for the sake of AppStream
    License: CC0-1.0

perhaps this is a mis-parsing of the debian/copyright file?  or something else?

**Comment by ximion** [comment]
Quaoting the error message:
> The metainfo file does not seem to be licensed under a permissive license. [...]

What matters is the software's metainfo file, or rather, what the file itself claims to be licensed under.
Looking into the metainfo file:
```xml
<component>
    <id>org.gnupg.scdaemon</id>
    <metadata_license>GPL</metadata_license>
[...]
```
Change the `metadata_license` license value to e.g. `FSFAP` (which is a tiny permissive license by the FSF for auxiliary files) or CC0-1.0 (if adding the license text doesn't bother you, AFAIK that's even included as default license in Debian now).

In any case, I think your `debian/copyright` file needs to be fixed too for that file ;-)

**Comment by dkg** [comment]
thanks for the pointer -- i'm the author of both `debian/copyright` and the metainfo file, but i'd missed the `metadata_license` entry when i relicensed the file to CC0-1.0.  I'll fix this by changing `metadata_license` :)

I've also opened https://bugs.debian.org/907072 so that lintian might be able to catch more of these issues automatically.

Thanks for your work on appstream!

**Comment by ximion** [comment]
> I've also opened https://bugs.debian.org/907072 so that lintian might be able to catch more of these issues automatically.

Oh, that is really great! Thank you!
