### ISSUE TITLE
unit test failure with v0.8.1 on Fedora due to missing ffprobe

### ISSUE THREAD

**Issue by Conan-Kudo** [ximion/appstream-generator#72]
When trying to update appstream-generator to v0.8.1, I got this failure when running the tests:

```
TEST: RpmMDPackageIndex
--- stderr ---
2020-03-19T19:25:08.683 [info] hashmap.d:995:__unittest_L991_C7 Testing hash tables
core.exception.AssertError@../src/asgen/handlers/screenshothandler.d(452): Assertion failure
----------------
??:? _d_assert [0x7f7ca793c4dc]
screenshothandler.d:452 void asgen.handlers.screenshothandler.__unittest_L436_C1() [0x752a32]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo*) [0x7f7ca7944be8]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x7f7ca7971e3a]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x7f7ca7973128]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x7f7ca7971dcb]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x7f7ca795dc0e]
??:? runModuleUnitTests [0x7f7ca7944a94]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f7ca7968e8a]
??:? _d_run_main2 [0x7f7ca7968cce]
??:? _d_run_main [0x7f7ca7968b3d]
entrypoint.d:35 main [0x63fbfc]
??:? __libc_start_main [0x7f7ca76b3041]
??:? _start [0x63fa7d]
1/26 unittests FAILED
-------
```

The full test log file from Meson is here: [appstream-generator-0.8.1-meson-testlog.txt](https://github.com/ximion/appstream-generator/files/4357322/appstream-generator-0.8.1-meson-testlog.txt)

**Comment by Conan-Kudo** [comment]
This looks like it's choking because ffprobe wasn't detected. This test should probably succeed with warning when ffprobe is unavailable.

**Comment by ximion** [comment]
I don't think a test should implicitly be skipped... Giving a more helpful error message is something I'd like to have though.

**Comment by Conan-Kudo** [comment]
The test isn't ever going to pass because Fedora doesn't have ffmpeg in its repositories. Unless you want to adjust it to use something we _do_ have?

**Comment by ximion** [comment]
Fedora doesn't have ffmpeg? Why? A ton of stuff depends on that...

**Comment by Conan-Kudo** [comment]
It's always lacked FFmpeg because of the complex situation with multimedia codecs that it bundles.

**Comment by ximion** [comment]
Fedora is weird - even Debian (!), Ubuntu and openSUSE have ffmpeg.
In any case though, this is a valid reason to make this test optional, since asgen can used without ffprobe with little functionality loss.
