### ISSUE TITLE
Package silently ignored

### ISSUE THREAD

**Issue by City-busz** [ximion/appstream-generator#84]
I have a package on Arch Linux with valid desktop and appdata files, but the package is completely missing from the output of appstream-generator: [vokoscreen](https://www.archlinux.org/packages/community/x86_64/vokoscreen/download/)

It doesn't even mention that could be interesting or no interesting files found. No hints or anything else, so I have no idea what actually happens. I didn't experience something like this with other packages.

Also, it would be great so see a way to test individual packages for compliance with apptream-generator without processing the whole repository.

**Comment by ximion** [comment]
Do you have a verbose log from the generator run?
The only packages that are silently ignored are ones without any metadata, but this package clearly has metadata in the right locations.
Processing individual packages without a repository is tricky, as doing so won't yield the same result (icons may be split out to different packages, so may be translations, and icon themes may also be different)

**Comment by City-busz** [comment]
I ran `appstream-generator` with `--verbose` again from the scratch, but I can't see anything related to vokoscreen on the output. But it seems that the package is processed somehow, because when I ran `grep -Ril vokoscreen` or `grep -Ril vokoscreenNG.desktop` on the output folder, I get this:
`db/contents/data.mdb`

**Comment by ximion** [comment]
Run `appstream-generator forget vokoscreen` so the package is actually gone and not cached anymore, and then reprocess in verbose mode to get more information.

**Comment by City-busz** [comment]
I still get nothing. Also I can't get any info about the package:
```
$ appstream-generator info vokoscreen/3.0.4-2/x86_64 --verbose
2020-07-06 20:34:38 - DEBUG: Using `optipng`: /usr/bin/optipng
2020-07-06 20:34:38 - ERROR: Disabled feature `screenshotVideos`: The `ffprobe` binary was not found.
2020-07-06 20:34:38 - WARNING: Configuration does not permit downloading files. Several features will not be available.
2020-07-06 20:34:38 - WARNING: Metainfo validation has been disabled in configuration.
2020-07-06 20:34:38 - DEBUG: Using LMDB 0.9.25: (January 30, 2020) major=0 minor=9 patch=25
2020-07-06 20:34:38 - DEBUG: Opening contents cache.
== vokoscreen/3.0.4-2/x86_64 ==
Contents:
~ No contents found.

Icons:
~ No icons found.

Global Component IDs:

Generated Data:

Hints: None
```

**Comment by ximion** [comment]
Try just `appstream-generator info vokoscreen` - also, which version of libarchive do you have installed? Are any other Zstandard-compressed files processed?

**Comment by City-busz** [comment]
It does not accept it:
```
$ appstream-generator info vokoscreen
Please enter a package-id in the format <name>/<version>/<arch>
```
libarchive version:
```
pacman -Q libarchive
libarchive 3.4.3-1
```
All new packages entered into the official repositories are compressed with Zstandard, and I didn't see any problems with the other packages (I tested a lot).

**Comment by ximion** [comment]
After you ran `appstream-generator forget vokoscreen` you should have gotten some kind of reprocessing messages... Can you give me the output of that command and the process command, both in verbose mode? (attach if the text is too long)

**Comment by City-busz** [comment]
Here is the log: [appstream-generator.log](https://github.com/ximion/appstream-generator/files/4881454/appstream-generator.log)

**Comment by City-busz** [comment]
I configured a local test repository, added the same vokoscreen package, and now it processed fine by appstream-generator.
I'll rebuild the package in the official repositories and check the result.

**Comment by City-busz** [comment]
It seems that something wrong with the repo sync, so it's probably not a bug in appstream-generator.

At least I figured out how to test appstream-generator with a small test repository.
Thanks!

**Comment by ximion** [comment]
Yeah, I just tried to reproduce the issue locally and couldn't. A repo sync problem would explain it though, thanks for investigating this further! :-)
