### ISSUE TITLE
Metainfo files are ignored for Elementary OS apps

### ISSUE THREAD

**Issue by City-busz** [ximion/appstream-generator#88]
I usually get 'no-metainfo' warnings for Elementary OS applications. The metainfo file is ignored by appstream-generator, and just the desktop file is processed. Tested apps (on Arch Linux) with their metainfo files:
- [bookworm](https://github.com/babluboy/bookworm/blob/master/data/com.github.babluboy.bookworm.appdata.xml.in)
- [ciano](https://github.com/robertsanseries/ciano/blob/master/data/com.github.robertsanseries.ciano.appdata.xml.in)
- [minder](https://github.com/phase1geo/Minder/blob/master/data/com.github.phase1geo.minder.appdata.xml.in)
- [notes-up](https://github.com/Philip-Scott/Notes-up/blob/master/data/com.github.philip-scott.notes-up.appdata.xml)
- [pdftricks](https://github.com/muriloventuroso/pdftricks/blob/master/data/com.github.muriloventuroso.pdftricks.appdata.xml.in)
- [spice-up](https://github.com/Philip-Scott/Spice-up/blob/master/data/com.github.philip-scott.spice-up.appdata.xml)
- [torrential](https://github.com/davidmhewitt/torrential/blob/master/data/com.github.davidmhewitt.torrential.appdata.xml)
- [vocal](https://github.com/needle-and-thread/vocal/blob/master/data/com.github.needleandthread.vocal.appdata.xml)

It seems that when I specify the corresponding desktop file explicitly in the metainfo file with the `<launchable type="desktop-id">` tag, it solves the problem.

Elementary OS applications usually use the same name for desktop and metainfo files , e.g.:
- desktop file: `/usr/share/applications/com.github.davidmhewitt.torrential.desktop`
- metainfo file: `/usr/share/metainfo/com.github.davidmhewitt.torrential.appdata.xml`

So could appstream-generator handle these applications better, or is the `<launchable>` tag necessarily for the pairing?

**Comment by ximion** [comment]
The `<launchable>` tag is mandatory, but we did have some workaround in place to just check "ID + .desktop" as heuristic for finding desktop-entry files. That probably broke in the move to more ascompose components, I'll have a look if it's feasible to add this feature back.
Adding `launchable` tags is a good idea in any case though :-)

**Comment by City-busz** [comment]
I found the problem! `cid ~ ".desktop"` is not removed from desktop list, so it processed twice, and the latter overwrites the previous data loaded from metainfo. See #91 for a simple fix.
